spring:
  application:
    name: ngn-financial-calculator-backend
  profiles:
    default: local

  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:6033/ngn_calc?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:123456}
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true

  session:
    store-type: redis
    redis:
      namespace: spring:session:ngn_calc

  lifecycle:
    timeout-per-shutdown-phase: 30s

server:
  port: ${SERVER_PORT:8080}
  forward-headers-strategy: framework
  shutdown: graceful
  servlet:
    session:
      cookie:
        http-only: true
        same-site: ${SESSION_COOKIE_SAME_SITE:lax}
        secure: ${SESSION_COOKIE_SECURE:true}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true
      show-details: when_authorized
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true

cors:
  config:
    allowed-origins: ${CORS_ALLOWED_ORIGINS}
    allowed-methods: ${CORS_ALLOWED_METHODS:GET,POST,PUT,DELETE}
    allowed-headers: ${CORS_ALLOWED_HEADERS:authorization,content-type,x-auth-token,x-app-brand}
    exposed-headers: ${CORS_EXPOSED_HEADERS:x-auth-token}
    allow-credentials: ${CORS_ALLOW_CREDENTIALS:true}

rate:
  limiting:
    capacity: ${RATE_LIMIT_CAPACITY:20}
    refillInterval: ${RATE_LIMIT_REFILL_INTERVAL:PT1M}
    refillTokens: ${RATE_LIMIT_REFILL_TOKENS:20}
